spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

app:
  jwt:
    secret: ${JWT_SECRET}
  gemini:
    api-key: ${GEMINI_API_KEY}

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    com.projectarchitect: INFO
